normal_to_moew: dict = {
  "A": "moew",
  "B": "Miaw",
  "C": "Moew",
  "D": "miaw",
  "E": "mOew",
  "F": "moEw",
  "G": "moeW",
  "H": "MOew",
  "I": "MoEw",
  "J": "MoeW",
  'K': "mOEww",
  'L': "mOeW",
  'M': "mOEw",
  "N": 'MOEw',
  'O': "mOEW",
  'P': "MOEW",
  'Q': "mIaw",
  'R': 'miAw',
  'S': "miaW",
  "T": "MIaww",
  'U': "MiAww",
  'V': "MiaWw",
  'W': "MIaw",
  'X': "MiAw",
  'Y': "MiaW",
  'Z': 'MIAw',
  ' ': 'MIAW',
  '.': "Meh",
  ',': 'MEH'
}

moew_to_normal: dict = {
  "moew": "A",
  "Miaw": "B",
  "Moew": "C",
  "miaw": "D",
  "mOew": "E",
  "moEw": "F",
  "moeW": "G",
  "MOew": "H",
  "MoEw": "I",
  "MoeW": "J",
  'mOEww': "K",
  'mOeW': "L",
  'mOEw': "M",
  "MOEw": 'N',
  'mOEW': "O",
  'MOEW': "P",
  'mIaw': "Q",
  'miAw': 'R',
  'miaW': "S",
  "MIaww": "T",
  'MiAww': "U",
  'MiaWw': "V",
  'MIaw': "W",
  'MiAw': "X",
  'MiaW': "Y",
  'MIAw': 'Z',
  'MIAW': ' ',
  'Meh': ".",
  'MEH': ','
}
